import type { Metadata } from 'next'
import type { FC, ReactNode } from 'react'
import { JetBrains_Mono } from 'next/font/google'
import '@/styles/globals.css'
import { Header } from '@/components/header'
import { PageTransitions } from '@/components/page-transitions'
import { StairTransitions } from '@/components/stair-transition'

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrains-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}
const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-br">
      <body className={jetBrainsMono.variable}>
        <Header />
        <StairTransitions />
        <PageTransitions>{children}</PageTransitions>
      </body>
    </html>
  )
}

export default RootLayout
